### PR TITLE
Show filename and line number when template errors.

### PR DESCRIPTION
**Pull request by frodsan**
I made this for [tynn/render](https://github.com/frodsan/tynn/blob/master/lib/tynn/render.rb#L106..L121). Not sure if it's the best way, but definitely helps with debugging. Let me know what you think.

### CODE REVIEW

**Comment by eddiezane** [comment]
Any chance we can get this merged please?

**Comment by soveran** [comment]
@eddiezane I'll work on this and release a new version tomorrow.

**Comment by eddiezane** [comment]
@soveran thanks mate!

**Comment by soveran** [comment]
@eddiezane I just released version 1.2.0 and it includes this feature. Thanks for your patience!

**Comment by eddiezane** [comment]
@soveran you rock so hard! Thanks a ton!

**Pull request merged**
